### PR TITLE
updated to use prop-types to support newer version of React

### PR DESCRIPTION
**Pull request by XaxisJosh**
added prop-types devDep
updated babel-plugin-flow-react-proptypes

### CODE REVIEW

**Comment by InsidersByte** [comment]
Hi @XaxisJosh,

I just checked this out and it looks great, but I don't think it will work with older versions of React, as it requires `prop-types` to be installed, but it's not listed as a dependency or peerDependency. Installing it as a devDependency only works for running the demo site.

I would prefer to keep the backwards compatibility, but as it's a devDependency I don't think it should be a peerDependency or dependency. This issue might shed some light on this https://github.com/ReactTraining/react-router/issues/4960.

**Comment by XaxisJosh** [comment]
I'm unclear on what you are suggesting? Should I remove prop-types from the devDeps?

**Comment by InsidersByte** [comment]
Sorry, that's my fault. Can you move prop-types to be a dependency.

I checked out react-router-dom and that's what they have done (see
https://github.com/ReactTraining/react-router/blob/master/packages/react-router-dom/package.json)

**Comment by XaxisJosh** [comment]
@InsidersByte updated per your comments.

**Comment by InsidersByte** [comment]
awesome 👍

**Pull request merged**
